const RESTAURANT = {
  name: "Nami Sushi",
  tagline: "O sushi delivery nº 1 do norte da ilha",
  neighborhood: "Ingleses · Florianópolis",
  address: "Rua Rita Maria Garcia, 1500 — Ingleses Norte, Florianópolis/SC",
  phoneDisplay: "(48) 98804-1041",
  whatsapp: "5548988041041",
  hours: "11h às 23h59",
  deliveryTime: "45–55 min",
  rating: "4.8",
  reviews: "1.273 notas",
  deliveryFee: 7.9,
  freeDeliveryFrom: 99,
};

const CATEGORIES = [
  { id: "sucessos", label: "Sucessos" },
  { id: "individuais", label: "Individuais" },
  { id: "casal", label: "Para 2" },
  { id: "familia", label: "Família" },
  { id: "temakis", label: "Temakis" },
  { id: "hots", label: "Hots" },
  { id: "uramakis", label: "Uramakis" },
  { id: "dyos", label: "Dyos" },
  { id: "pokes", label: "Pokes" },
  { id: "entradas", label: "Entradas" },
  { id: "bebidas", label: "Bebidas" },
];

const MENU = [
  {
    id: "mikasa",
    category: "sucessos",
    name: "Combinado Mikasa",
    pieces: "17 peças",
    desc: "Todo de salmão: 3 sashimis, 6 uramakis filadélfia, 4 dyos e 4 hossomakis de salmão.",
    price: 54,
    image: "img/combo3.jpg",
    badge: "Mais pedido",
  },
  {
    id: "dia4",
    category: "sucessos",
    name: "Combinado do Dia 4",
    pieces: "53 peças",
    desc: "O mais pedido da casa. 10 uramaki salmão filadélfia, pastinha, skin, kani e hossomakis.",
    price: 80,
    image: "img/combo2.jpg",
  },
  {
    id: "mega-dia",
    category: "sucessos",
    name: "Mega Combinado do Dia",
    pieces: "110 peças",
    desc: "20 uramaki salmão, 10 camarão, 5 califórnia, 12 hot, niguiris e hossomakis.",
    price: 140,
    image: "img/hero.jpg",
    badge: "Família",
  },
  {
    id: "mizuki",
    category: "sucessos",
    name: "Combinado Mizuki",
    pieces: "72 peças",
    desc: "Lançamento sem kani. Uramaki salmão, hot filadélfia, niguiri skin, pastinha e hossos.",
    price: 110,
    image: "img/combo2.jpg",
    badge: "Novo",
  },
  {
    id: "kioto",
    category: "sucessos",
    name: "Combinado Kioto",
    pieces: "20 peças",
    desc: "Individual caprichado: uramakis de salmão, skin e kani + niguiris.",
    price: 46,
    image: "img/nigiri.jpg",
  },
  {
    id: "yakisoba-promo",
    category: "sucessos",
    name: "Yakissoba 600g",
    pieces: "Promoção 40% off",
    desc: "Yakissoba generoso com legumes e molho especial da casa.",
    price: 38,
    image: "img/yakisoba.jpg",
    badge: "40% off",
  },
  {
    id: "sakurai",
    category: "individuais",
    name: "Combinado Sakurai",
    pieces: "19 peças",
    desc: "Seleção clássica para uma pessoa, com uramakis, hossomakis e niguiris.",
    price: 45,
    image: "img/combo.jpg",
  },
  {
    id: "umai",
    category: "individuais",
    name: "Combinado Umai",
    pieces: "22 peças",
    desc: "Variado e bem servido, com salmão, kani e skin.",
    price: 54,
    image: "img/combo2.jpg",
  },
  {
    id: "yoshi",
    category: "individuais",
    name: "Combinado Yoshi",
    pieces: "17 peças",
    desc: "Peças premium em porção individual, foco em salmão fresco.",
    price: 54,
    image: "img/combo3.jpg",
  },
  {
    id: "kondoi",
    category: "individuais",
    name: "Combinado Kondoi",
    pieces: "17 peças · +salmão",
    desc: "Individual com extra de salmão nas peças principais.",
    price: 54,
    image: "img/sashimi.jpg",
  },
  {
    id: "chirihama",
    category: "individuais",
    name: "Combinado Chirihama",
    pieces: "17 peças · +salmão",
    desc: "Salmão em destaque com uramakis filadélfia e niguiris.",
    price: 54,
    image: "img/nigiri.jpg",
  },
  {
    id: "hakari",
    category: "individuais",
    name: "Combinado Salmão Hakari",
    pieces: "32 peças",
    desc: "Quase só salmão: sashimis, uramakis e hots para quem não abre mão.",
    price: 80,
    image: "img/sashimi.jpg",
    badge: "Salmão",
  },
  {
    id: "sakana",
    category: "individuais",
    name: "Combinado Sakana",
    pieces: "18 peças + temaki",
    desc: "18 peças + 1 temaki ou kaki shake à escolha.",
    price: 82,
    image: "img/temaki.jpg",
  },
  {
    id: "sake-yume",
    category: "individuais",
    name: "Combinado Sake Yume",
    pieces: "40 peças",
    desc: "Sonho de salmão: 40 peças frescas para um jantar completo.",
    price: 130,
    image: "img/hero.jpg",
  },
  {
    id: "kitami",
    category: "casal",
    name: "Combinado Kitami",
    pieces: "37 peças",
    desc: "Ideal para duas pessoas. Mix de uramakis, hots e niguiris.",
    price: 85,
    image: "img/combo.jpg",
  },
  {
    id: "saitama",
    category: "casal",
    name: "Combinado Saitama",
    pieces: "33 peças",
    desc: "Seleção equilibrada para o casal, com salmão e camarão.",
    price: 95,
    image: "img/combo2.jpg",
  },
  {
    id: "shisui",
    category: "casal",
    name: "Combinado Shisui",
    pieces: "30 peças",
    desc: "Peças gourmet, incluindo hot e uramaki filadélfia.",
    price: 100,
    image: "img/hot.jpg",
  },
  {
    id: "shiga",
    category: "casal",
    name: "Combinado Shiga",
    pieces: "32 peças",
    desc: "Variado e caprichado, com sashimi e rolls clássicos.",
    price: 98,
    image: "img/combo3.jpg",
  },
  {
    id: "nagoya",
    category: "casal",
    name: "Combinado Nagoya",
    pieces: "48 peças",
    desc: "O favorito para dois com fome. 48 peças bem montadas.",
    price: 121,
    image: "img/hero.jpg",
    badge: "Casal",
  },
  {
    id: "mega-choji",
    category: "casal",
    name: "Mega Choji",
    pieces: "18 peças + temaki ou hot",
    desc: "18 peças e temaki ou hot grátis.",
    price: 84,
    image: "img/temaki.jpg",
  },
  {
    id: "charizard",
    category: "casal",
    name: "Mega Charizard",
    pieces: "36 peças",
    desc: "Combo generoso com rolls quentes e frios.",
    price: 96,
    image: "img/hot.jpg",
  },
  {
    id: "2temaki-hot",
    category: "casal",
    name: "2 Temakis + Hot Filadélfia",
    pieces: "Combo",
    desc: "Dois temakis à escolha e 1 porção de hot salmão filadélfia.",
    price: 66,
    image: "img/temaki.jpg",
  },
  {
    id: "2temaki-hot2",
    category: "casal",
    name: "2 Temakis + Hot (salmão e camarão)",
    pieces: "Combo",
    desc: "Temaki de salmão, temaki de camarão e 1 hot.",
    price: 70,
    image: "img/camarao.jpg",
  },
  {
    id: "sakai",
    category: "familia",
    name: "Combinado Sakai",
    pieces: "56 peças",
    desc: "Para até 4 pessoas. Variedade clássica da casa.",
    price: 106,
    image: "img/combo.jpg",
  },
  {
    id: "nishiama",
    category: "familia",
    name: "Combinado Nishiama",
    pieces: "48 peças",
    desc: "Peças maiores e mais premium, ideal para 3 pessoas.",
    price: 146,
    image: "img/combo2.jpg",
  },
  {
    id: "gifu",
    category: "familia",
    name: "Combinado Gifu",
    pieces: "80 peças",
    desc: "Mesa farta: 80 peças para reunir a família.",
    price: 195,
    image: "img/hero.jpg",
  },
  {
    id: "familia100",
    category: "familia",
    name: "Combo Família",
    pieces: "100 peças",
    desc: "100 peças para a mesa toda. O clássico da casa.",
    price: 182,
    image: "img/combo.jpg",
    badge: "Família",
  },
  {
    id: "premium",
    category: "familia",
    name: "Combinado Premium",
    pieces: "Seleção especial",
    desc: "O top da casa: cortes nobres, hot e sashimi de salmão.",
    price: 216,
    image: "img/sashimi.jpg",
    badge: "Premium",
  },
  {
    id: "temaki-salmao",
    category: "temakis",
    name: "Temaki Salmão Filadélfia",
    pieces: "1 cone",
    desc: "Salmão fresco, cream cheese e cebolinha no cone de alga.",
    price: 40,
    image: "img/temaki.jpg",
  },
  {
    id: "temaki-quente",
    category: "temakis",
    name: "Temaki Quente",
    pieces: "1 cone",
    desc: "Temaki empanado e frito, crocante por fora e cremoso por dentro.",
    price: 43,
    image: "img/hot.jpg",
    badge: "Quente",
  },
  {
    id: "temaki-skin",
    category: "temakis",
    name: "Temaki Skin Filadélfia",
    pieces: "1 cone",
    desc: "Pele de salmão crocante com cream cheese.",
    price: 38,
    image: "img/temaki.jpg",
  },
  {
    id: "temaki-camarao",
    category: "temakis",
    name: "Temaki Camarão Filadélfia",
    pieces: "1 cone",
    desc: "Camarão, cream cheese e toque de limão.",
    price: 40,
    image: "img/camarao.jpg",
  },
  {
    id: "temaki-camarao-mix",
    category: "temakis",
    name: "Temaki Camarão Mix Crocante",
    pieces: "1 cone",
    desc: "Camarão com mix crocante de cebola e cream cheese.",
    price: 40,
    image: "img/camarao.jpg",
  },
  {
    id: "temaki-camarao-spicy",
    category: "temakis",
    name: "Temaki Camarão Spicy",
    pieces: "1 cone",
    desc: "Camarão ao molho spicy da casa.",
    price: 40,
    image: "img/spicy.jpg",
  },
  {
    id: "temaki-ceviche",
    category: "temakis",
    name: "Temaki Ceviche de Salmão",
    pieces: "1 cone",
    desc: "Salmão marinado no limão, cebola roxa e coentro.",
    price: 40,
    image: "img/ceviche.jpg",
  },
  {
    id: "temaki-kani",
    category: "temakis",
    name: "Temaki Kani Filadélfia",
    pieces: "1 cone",
    desc: "Kani kama, cream cheese e alga crocante.",
    price: 31,
    image: "img/california.jpg",
  },
  {
    id: "temaki-ko",
    category: "temakis",
    name: "Temaki Kō",
    pieces: "1 cone",
    desc: "Receita especial da casa com salmão e finalização flambada.",
    price: 40,
    image: "img/temaki.jpg",
    badge: "Casa",
  },
  {
    id: "temaki-lula",
    category: "temakis",
    name: "Temaki Lula Filadélfia",
    pieces: "1 cone",
    desc: "Lula fresca, cream cheese e gergelim.",
    price: 39,
    image: "img/temaki.jpg",
  },
  {
    id: "temaki-massago",
    category: "temakis",
    name: "Temaki Massago Black",
    pieces: "1 cone",
    desc: "Ovas pretas, salmão e cream cheese.",
    price: 43,
    image: "img/spicy.jpg",
  },
  {
    id: "temaki-mushroom",
    category: "temakis",
    name: "Temaki Mushroom Filadélfia",
    pieces: "1 cone",
    desc: "Shitake grelhado e cream cheese. Opção sem peixe.",
    price: 39,
    image: "img/sunomono.jpg",
  },
  {
    id: "temaki-avocado",
    category: "temakis",
    name: "Temaki Salmão Avocado",
    pieces: "1 cone",
    desc: "Salmão, abacate cremoso e cream cheese.",
    price: 43,
    image: "img/temaki.jpg",
  },
  {
    id: "temaki-cali",
    category: "temakis",
    name: "Temaki Salmão Califórnia",
    pieces: "1 cone",
    desc: "Salmão, kani, pepino e cream cheese.",
    price: 40,
    image: "img/california.jpg",
  },
  {
    id: "temaki-couve",
    category: "temakis",
    name: "Temaki Salmão Crispy Couve",
    pieces: "1 cone",
    desc: "Salmão com couve crispy e cream cheese.",
    price: 40,
    image: "img/temaki.jpg",
  },
  {
    id: "temaki-skin-mix",
    category: "temakis",
    name: "Temaki Salmão Skin Mix",
    pieces: "1 cone",
    desc: "Salmão e skin crocante no mesmo cone.",
    price: 40,
    image: "img/temaki.jpg",
  },
  {
    id: "temaki-grelhado",
    category: "temakis",
    name: "Temaki Salmão Grelhado Filadélfia",
    pieces: "1 cone",
    desc: "Salmão grelhado, cream cheese e toque de shoyu.",
    price: 39,
    image: "img/nigiri.jpg",
  },
  {
    id: "hot-filadelfia",
    category: "hots",
    name: "Hot Salmão Filadélfia",
    pieces: "Porção",
    desc: "O clássico: salmão e cream cheese empanados e fritos.",
    price: 26,
    image: "img/hot.jpg",
    badge: "Clássico",
  },
  {
    id: "hot-chilli",
    category: "hots",
    name: "Hot Chilli Filadélfia",
    pieces: "12 peças",
    desc: "Hot picante com chilli e cream cheese.",
    price: 39,
    image: "img/hot.jpg",
  },
  {
    id: "hot-batata",
    category: "hots",
    name: "Hot Crispy Batata Doce",
    pieces: "Porção",
    desc: "Finalizado com chips de batata doce.",
    price: 27,
    image: "img/hot.jpg",
  },
  {
    id: "hot-kitkat",
    category: "hots",
    name: "Hot Kit Kat",
    pieces: "4 peças",
    desc: "Hot doce com chocolate. Sobremesa da casa.",
    price: 22,
    image: "img/hot.jpg",
    badge: "Doce",
  },
  {
    id: "hot-lemon",
    category: "hots",
    name: "Hot Salmão Lemon",
    pieces: "Porção",
    desc: "Salmão, cream cheese e toque cítrico de limão siciliano.",
    price: 25,
    image: "img/hot.jpg",
  },
  {
    id: "hot-alho",
    category: "hots",
    name: "Hot Crispy Alho Poró",
    pieces: "Porção",
    desc: "Crocante de alho poró por cima do hot de salmão.",
    price: 27,
    image: "img/hot.jpg",
  },
  {
    id: "hot-camarao",
    category: "hots",
    name: "Hot Camarão Crocante",
    pieces: "Porção",
    desc: "Novo: camarão empanado, cream cheese e crispy.",
    price: 36,
    image: "img/camarao.jpg",
    badge: "Novo",
  },
  {
    id: "hot-banana",
    category: "hots",
    name: "Hot de Banana",
    pieces: "4 peças",
    desc: "Banana, cream cheese e toque de canela. Doce.",
    price: 19,
    image: "img/hot.jpg",
  },
  {
    id: "hot-wafer",
    category: "hots",
    name: "Hot Wafer",
    pieces: "4 peças",
    desc: "Hot doce com wafer crocante.",
    price: 21,
    image: "img/hot.jpg",
  },
  {
    id: "hot-couve",
    category: "hots",
    name: "Hot Crispy Couve",
    pieces: "Porção",
    desc: "Hot de salmão com couve crispy.",
    price: 27,
    image: "img/hot.jpg",
  },
  {
    id: "ura-romeu",
    category: "uramakis",
    name: "Uramaki Romeu e Julieta",
    pieces: "4 peças",
    desc: "Goiabada e cream cheese. Doce e salgado.",
    price: 24,
    image: "img/uramaki.jpg",
  },
  {
    id: "ura-spicy",
    category: "uramakis",
    name: "Uramaki Salmão Spicy",
    pieces: "4 peças",
    desc: "Salmão ao molho spicy e cream cheese.",
    price: 20,
    image: "img/spicy.jpg",
  },
  {
    id: "ura-camarao",
    category: "uramakis",
    name: "Uramaki Camarão Crocante",
    pieces: "4 peças",
    desc: "Camarão crocante enrolado no arroz e gergelim.",
    price: 17,
    image: "img/camarao.jpg",
  },
  {
    id: "ura-kani",
    category: "uramakis",
    name: "Uramaki Kani Filadélfia",
    pieces: "4 peças",
    desc: "Kani e cream cheese.",
    price: 16,
    image: "img/california.jpg",
  },
  {
    id: "ura-lula",
    category: "uramakis",
    name: "Uramaki Lula Filadélfia",
    pieces: "4 peças",
    desc: "Lula fresca e cream cheese.",
    price: 19,
    image: "img/uramaki.jpg",
  },
  {
    id: "ura-pastinha",
    category: "uramakis",
    name: "Uramaki Pastinha Salmão Spicy",
    pieces: "4 peças",
    desc: "Pastinha de salmão picante.",
    price: 15,
    image: "img/spicy.jpg",
  },
  {
    id: "ura-massago",
    category: "uramakis",
    name: "Uramaki Salmão Massago",
    pieces: "4 peças",
    desc: "Salmão com ovas de massago.",
    price: 20,
    image: "img/uramaki.jpg",
  },
  {
    id: "ura-shitake",
    category: "uramakis",
    name: "Uramaki Shitake Filadélfia",
    pieces: "4 peças",
    desc: "Shitake grelhado e cream cheese.",
    price: 19,
    image: "img/sunomono.jpg",
  },
  {
    id: "ura-skin",
    category: "uramakis",
    name: "Uramaki Skin Filadélfia",
    pieces: "4 peças",
    desc: "Skin crocante e cream cheese.",
    price: 16,
    image: "img/uramaki.jpg",
  },
  {
    id: "ura-rucula",
    category: "uramakis",
    name: "Uramaki Skin Rúcula",
    pieces: "4 peças",
    desc: "Skin, rúcula e cream cheese.",
    price: 18,
    image: "img/california.jpg",
  },
  {
    id: "dyo-couve",
    category: "dyos",
    name: "Dyo Couve Crispy",
    pieces: "2 peças",
    desc: "Salmão sobre arroz com couve crispy.",
    price: 16,
    image: "img/dyo.jpg",
  },
  {
    id: "dyo-cebola",
    category: "dyos",
    name: "Dyo Crispy de Cebola",
    pieces: "2 peças",
    desc: "Salmão e crispy de cebola.",
    price: 16,
    image: "img/nigiri.jpg",
  },
  {
    id: "dyo-brie",
    category: "dyos",
    name: "Dyo Salmão com Queijo Brie",
    pieces: "2 peças",
    desc: "Salmão e queijo brie derretido.",
    price: 18,
    image: "img/nigiri.jpg",
  },
  {
    id: "dyo-massago",
    category: "dyos",
    name: "Dyo Massago Black",
    pieces: "2 peças",
    desc: "Ovas pretas sobre salmão.",
    price: 21,
    image: "img/sashimi.jpg",
  },
  {
    id: "dyo-trad",
    category: "dyos",
    name: "Dyo Tradicional",
    pieces: "2 peças",
    desc: "O dyo clássico de salmão.",
    price: 17,
    image: "img/nigiri.jpg",
  },
  {
    id: "dyo-var",
    category: "dyos",
    name: "Dyo Variados",
    pieces: "12 peças",
    desc: "Seleção da casa com 12 dyos diferentes.",
    price: 60,
    image: "img/combo3.jpg",
  },
  {
    id: "dyo-ko",
    category: "dyos",
    name: "Dyo Flambado Kō",
    pieces: "4 peças",
    desc: "Flambado na hora, receita especial Kō.",
    price: 20,
    image: "img/nigiri.jpg",
    badge: "Flambado",
  },
  {
    id: "dyo-goiaba",
    category: "dyos",
    name: "Dyo Goiabada Especial",
    pieces: "4 peças",
    desc: "Lançamento: goiabada e cream cheese.",
    price: 23,
    image: "img/dyo.jpg",
    badge: "Novo",
  },
  {
    id: "dyo-ko2",
    category: "dyos",
    name: "Dyo Kō",
    pieces: "2 peças",
    desc: "Assinatura da casa em duas peças.",
    price: 19,
    image: "img/nigiri.jpg",
  },
  {
    id: "dyo-doritos",
    category: "dyos",
    name: "Dyo Doritos",
    pieces: "2 peças",
    desc: "Salmão com crocante de Doritos.",
    price: 17,
    image: "img/dyo.jpg",
  },
  {
    id: "dyo-wasabi",
    category: "dyos",
    name: "Dyo Wasabi",
    pieces: "2 peças",
    desc: "Salmão com toque intenso de wasabi.",
    price: 17,
    image: "img/sashimi.jpg",
  },
  {
    id: "dyo-cam-spicy",
    category: "dyos",
    name: "Dyo Camarão Spicy",
    pieces: "2 peças",
    desc: "Camarão ao molho spicy.",
    price: 17,
    image: "img/camarao.jpg",
  },
  {
    id: "dyo-caprese",
    category: "dyos",
    name: "Dyo Caprese",
    pieces: "2 peças",
    desc: "Tomate, mussarela de búfala e manjericão.",
    price: 17,
    image: "img/sunomono.jpg",
  },
  {
    id: "dyo-tamago",
    category: "dyos",
    name: "Dyo Tamago",
    pieces: "2 peças",
    desc: "Omelete japonês doce sobre o arroz.",
    price: 19,
    image: "img/nigiri.jpg",
  },
  {
    id: "poke-cheff",
    category: "pokes",
    name: "Poke do Cheff",
    pieces: "Bowl",
    desc: "Montagem do chef com salmão, arroz, molho da casa e acompanhamentos.",
    price: 61,
    image: "img/poke.jpg",
    badge: "Chef",
  },
  {
    id: "poke-480",
    category: "pokes",
    name: "Poke Personalizado 480ml",
    pieces: "480 ml",
    desc: "Monte o seu: base, proteína e toppings.",
    price: 55,
    image: "img/poke.jpg",
  },
  {
    id: "poke-600",
    category: "pokes",
    name: "Poke Personalizado 600ml",
    pieces: "600 ml",
    desc: "Versão grande do poke personalizado.",
    price: 65,
    image: "img/poke.jpg",
  },
  {
    id: "poke-fit",
    category: "pokes",
    name: "Poke Fitness",
    pieces: "Bowl",
    desc: "Mais leve: menos arroz, mais folhas, salmão e edamame.",
    price: 44,
    image: "img/sunomono.jpg",
  },
  {
    id: "poke-tamago",
    category: "pokes",
    name: "Poke Tamago",
    pieces: "Bowl",
    desc: "Poke com omelete japonês, salmão e molho especial.",
    price: 66,
    image: "img/poke.jpg",
  },
  {
    id: "sunomono",
    category: "entradas",
    name: "Sunomono",
    pieces: "Porção",
    desc: "Pepino agridoce clássico japonês.",
    price: 15,
    image: "img/sunomono.jpg",
  },
  {
    id: "suno-kani",
    category: "entradas",
    name: "Sunomono Kani em Cubos",
    pieces: "Porção",
    desc: "Sunomono com kani em cubos.",
    price: 21,
    image: "img/sunomono.jpg",
  },
  {
    id: "suno-salmao",
    category: "entradas",
    name: "Sunomono Salmão",
    pieces: "Porção",
    desc: "Pepino agridoce com cubos de salmão fresco.",
    price: 31,
    image: "img/sashimi.jpg",
  },
  {
    id: "ceviche-salmao",
    category: "entradas",
    name: "Ceviche de Salmão",
    pieces: "Porção",
    desc: "Salmão marinado no limão, pimenta e cebola roxa.",
    price: 40,
    image: "img/ceviche.jpg",
  },
  {
    id: "ceviche-branco",
    category: "entradas",
    name: "Ceviche de Peixe Branco",
    pieces: "Porção",
    desc: "Peixe branco fresco ao leite de tigre.",
    price: 36,
    image: "img/ceviche.jpg",
  },
  {
    id: "nigiri-shitake",
    category: "entradas",
    name: "Nigiri de Shitake",
    pieces: "Porção",
    desc: "Shitake grelhado sobre arroz temperado.",
    price: 30,
    image: "img/nigiri.jpg",
  },
  {
    id: "batata-frita",
    category: "entradas",
    name: "Batata Frita",
    pieces: "1000 ml",
    desc: "Porção família de batata frita crocante.",
    price: 20,
    image: "img/batata.jpg",
  },
  {
    id: "camarao-croc",
    category: "entradas",
    name: "Porção de Camarão Crocante",
    pieces: "16 unidades",
    desc: "Camarões empanados e sequinhos.",
    price: 52,
    image: "img/camarao.jpg",
  },
  {
    id: "coca-600",
    category: "bebidas",
    name: "Coca-Cola 600ml",
    pieces: "Garrafa",
    desc: "Gelada, para acompanhar o pedido.",
    price: 10,
    image: "img/refri.jpg",
  },
  {
    id: "coca-zero-lata",
    category: "bebidas",
    name: "Coca-Cola Zero 310ml",
    pieces: "Lata",
    desc: "Zero açúcar.",
    price: 7,
    image: "img/refri.jpg",
  },
  {
    id: "coca-zero-2l",
    category: "bebidas",
    name: "Coca-Cola Zero 2L",
    pieces: "2 litros",
    desc: "Para dividir com a mesa.",
    price: 15,
    image: "img/refri.jpg",
  },
  {
    id: "agua",
    category: "bebidas",
    name: "Água sem gás",
    pieces: "500 ml",
    desc: "Água mineral.",
    price: 4,
    image: "img/agua.jpg",
  },
  {
    id: "agua-gas",
    category: "bebidas",
    name: "Água com gás",
    pieces: "500 ml",
    desc: "Água mineral com gás.",
    price: 4,
    image: "img/agua.jpg",
  },
  {
    id: "heineken",
    category: "bebidas",
    name: "Heineken Long Neck",
    pieces: "330 ml",
    desc: "Cerveja gelada.",
    price: 15,
    image: "img/cerveja.jpg",
  },
  {
    id: "combo-heineken",
    category: "bebidas",
    name: "Combo 4 Heineken",
    pieces: "Pague 3",
    desc: "4 long necks pelo preço de 3.",
    price: 45,
    image: "img/cerveja.jpg",
    badge: "Combo",
  },
  {
    id: "combo-bud",
    category: "bebidas",
    name: "Combo 4 Budweiser",
    pieces: "Long neck",
    desc: "Combo de 4 Budweiser geladas.",
    price: 40,
    image: "img/cerveja.jpg",
  },
  {
    id: "delvalle-pessego",
    category: "bebidas",
    name: "Del Valle Pêssego 290ml",
    pieces: "Lata",
    desc: "Néctar de pêssego.",
    price: 5,
    image: "img/suco.jpg",
  },
  {
    id: "delvalle-maracuja",
    category: "bebidas",
    name: "Suco de Maracujá Del Valle 290ml",
    pieces: "Lata",
    desc: "Néctar de maracujá.",
    price: 5,
    image: "img/suco.jpg",
  },
  {
    id: "macro-300",
    category: "bebidas",
    name: "Suco Macrovita 300ml",
    pieces: "300 ml",
    desc: "Suco natural da linha Macrovita.",
    price: 5,
    image: "img/suco.jpg",
  },
  {
    id: "macro-900",
    category: "bebidas",
    name: "Suco Macrovita 900ml",
    pieces: "900 ml",
    desc: "Garrafa média.",
    price: 11,
    image: "img/suco.jpg",
  },
  {
    id: "macro-1500",
    category: "bebidas",
    name: "Suco Macrovita 1500ml",
    pieces: "1,5 L",
    desc: "Garrafa família.",
    price: 20,
    image: "img/suco.jpg",
  },
];
